        

#include "AdhesiveSatPlugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;


auto adhesiveSatProxy = registerPlugin<Plugin,AdhesiveSatPlugin>(
	"AdhesiveSat", 
	"Autogenerated plugin - Base plugin created by Michael Getz, modified by Levi and Leonardo", 
	&Simulator::pluginManager
);


